# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm" # For npm packages
    directory: "/" # Location of package.json
    schedule:
      interval: "daily" # Check for updates daily

  - package-ecosystem: "github-actions" # For GitHub Actions
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "daily" # Check for updates daily

  # Add other package ecosystems as needed
